<hr />
<div class="jumbotron">
add group<br/>
------------<br/>

show groups here<br/>
---------------<br/>
edit group<br/>
delete group<br/>
<?php

// BEGIN showing the form
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('group'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
// END showing the form

if($message = $this->message){
	echo $message;
}
?>
</div>
<a href="<?php echo $this->url('social'); ?>" class="btn btn-success"><?php echo $this->translate('Back to my wall'); ?></a>
