<hr />
<div class="jumbotron">
<h2><?php echo $this->translate('Find people you may know'); ?></h2>
<?php
// BEGIN showing the form
$findPersonForm = $this->findPersonForm;
$findPersonForm->prepare();

echo $this->form()->openTag($findPersonForm);
echo $this->formRow($findPersonForm->get('search'));
echo $this->formSubmit($findPersonForm->get('submit'));
echo $this->form()->closeTag();
// END showing the form

$resultSearch = $this->resultSearch;
$searchFor = $this->search;
?>

<?php
if($resultSearch){

	if(($count = count($resultSearch)) != 1){
	
		echo $count.$this->translate(' people found with ').'"'.$searchFor.'"'.$this->translate(' in their name:<br/>');
	}else{
		echo $count.$this->translate(' person found with ').'"'.$searchFor.'"'.$this->translate(' in their name:<br/>');
	}

	foreach($resultSearch as $res){
	?>
	<div style="border: solid 0px #ADFF2F; box-shadow: 0px 0px 5px rgba(125, 213, 66, 1); border-radius: 0px;padding: 10px; width: 320px; height: auto; background: #fff; float: left; margin-left: 15px; margin-top: 15px; " onMouseOver="this.style.boxShadow='0px 0px 5px rgba(0, 80, 133, 1)'" onMouseOut="this.style.boxShadow='0px 0px 5px rgba(125, 213, 66, 1)'">
	<?php
		echo $res['firstName'].' '.$res['lastName'];
		echo '<br/><a href="add-person/'.$res['id'].'">'.$this->translate('Add').'</a>';
	?>
	</div>
	<?php
	}
	?>
	<div style="clear: both"></div><br/>
	<?php
}else{
	echo sprintf($this->message, '"'.$searchFor.'"');
}
?>
</div>
<a href="<?php echo $this->url('social'); ?>" class="btn btn-success"><?php echo $this->translate('Back to my wall'); ?></a>