<hr />
<div class="jumbotron">
<?php

if($message = $this->message){
	echo $message;
}
if($this->person){
?>
	<a href="<?php echo $this->url('add-person');?>" class="btn btn-success"><?php echo $this->translate('Add this person'); ?></a>
<?php
}
?>
</div>
<a href="<?php echo $this->url('social'); ?>" class="btn btn-success"><?php echo $this->translate('Back to my wall'); ?></a>
<a href="<?php echo $this->url('find-people'); ?>" class="btn btn-success"><?php echo $this->translate('Find more people'); ?></a>
