<hr />
<div class="jumbotron">

<?php
// BEGIN showing the form
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div style="position: relative;">';
echo '<div style="position: relative; float: left; ">';
echo $this->formRow($form->get('title'));
echo '<br/>';
echo $this->formRow($form->get('text'));
echo '</div>';
echo '<div style="clear: both"></div>';
echo $this->formSubmit($form->get('submit'));
echo '</div>';
echo $this->form()->closeTag();
// END showing the form

if($message = $this->message){
	echo '<div style="color: red">'.$message.'</div>';
}
?>


</div>
<a href="<?php echo $this->url('view-article/default', array('controller' => 'index', 'action'=>'view-article', 'id' => $this->id)).'#comments'; ?>" class="btn btn-success"><?php echo $this->translate('Back to comments'); ?></a>
