<hr />
<div class="jumbotron">

<?php
// BEGIN showing the form
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div style="position: relative;">';
echo '<div style="position: relative; float: left; ">';
echo $this->formRow($form->get('title'));
echo '<br/>';
echo $this->formRow($form->get('event'));
echo '</div>';
echo $this->formSubmit($form->get('submit'));
echo '</div>';
echo $this->form()->closeTag();
// END showing the form

if($message = $this->message){
?>
	<div style="color: red">
		<?php echo $message; ?>
	</div>
<?php
}
?>


</div>
<a href="<?php echo $this->url('social'); ?>" class="btn btn-success"><?php echo $this->translate('Back to my wall'); ?></a>
