<hr />
<div class="jumbotron">
<h2>Find people you may know</h2>
<?php
// BEGIN showing the form
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('search'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
// END showing the form

if($message = $this->message){
	echo $message;
}
if($this->person){

$formAddPerson = $this->formAddPerson;
$formAddPerson->setAttribute('action', $this->url('add-person'));
$formAddPerson->prepare();
echo $this->form()->openTag($formAddPerson);

echo $this->formRow($formAddPerson->get('addPerson'));
echo $this->formSubmit($formAddPerson->get('submit'));
echo $this->form()->closeTag();

}
?>
</div>
<a href="<?php echo $this->url('social'); ?>" class="btn btn-success"><?php echo $this->translate('Back to my wall'); ?></a>
