<h1><a href="<?php echo $this->url('login'); ?>"><span class="zf-green""><?php echo $this->escapeHtml($user->getUsername()); ?>'s</span></a> Social Wall</h1>
<a href="#" class="btn btn-success" style="float:right; position: relative;">Manage your groups</a>
<div style="clear: both"></div>
<hr />
<h4>You follow:</h4>
<hr />
<h4>They follow you:</h4>
<hr />
<div class="jumbotron">
Add event:
<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('event'));
echo '<br />Share with:<br />';
echo $this->formRow($form->get('followers'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>
</div>
<hr />
<h4 style="text-align:center">Events: <span><a href="#" class="btn btn-success">All</a> <a href="#" class="btn btn-success">My</a> <a href="#" class="btn btn-success">Group1</a> <a href="#" class="btn btn-success">Group2</a> <a href="#" class="btn btn-success">Group3</a></span></h4>
<div class="jumbotron">
<div style="border: dashed 3px #ADFF2F; border-radius: 15px;padding: 10px; width: 470px; height: 200px; float: left;">Event 1</div>
<div style="border: dashed 3px #ADFF2F; border-radius: 15px;padding: 10px; width: 470px; height: 200px; float: left; margin-left: 55px;">Event 2</div>
<div style="border: dashed 3px #ADFF2F; border-radius: 15px;padding: 10px; width: 470px; height: 200px; float: left; margin-top: 30px;">Event 3</div>
<div style="border: dashed 3px #ADFF2F; border-radius: 15px;padding: 10px; width: 470px; height: 200px; float: left; margin-top: 30px; margin-left: 55px;">Event 4</div>
<div style="border: dashed 3px #ADFF2F; border-radius: 15px;padding: 10px; width: 470px; height: 200px; float: left; margin-top: 30px;">Event 5</div>
<div style="border: dashed 3px #ADFF2F; border-radius: 15px;padding: 10px; width: 470px; height: 200px; float: left; margin-top: 30px; margin-left: 55px;">Event 6</div>
<div style="clear: both"></div>
</div>
