<h1 style="float: left">
	<a href="<?php echo $this->url('editProfile'); ?>">
		<span class="zf-green"><?php echo $this->escapeHtml($user->getDisplayName()); ?>'s</span>
	</a> Social Wall
</h1>
<a href="#" class="btn btn-success" style="float:right; position: relative; margin-top: 20px;">Manage your groups</a>
<div style="clear: both"></div>
<hr />
<h4>Мessages shelf: (here you'll see new messages) - NOT READY YET</h4> 
<span style="color: #b30606">Message for deletion 1</span><a href="">[x]</a> | 
<span style="color: #b30606">You have new follower!</span><a href="">[x]</a>
<hr />
<h4>You follow: (<a href="<?php echo $this->url('find-people');?>"><?php echo $this->translate('find more people to follow'); ?></a>)</h4>
<?php 
// BEGIN showing friends and following
foreach ($this->myFriends as $myFriend) {
	
	echo '<span class="zf-green">'.$myFriend->getDisplayName(). '</span>';
	echo '<a href="'.$this->url('delete-person/default', array('controller' => 'index', 'action'=>'delete-person', 'id' => $myFriend->getId())).'" 
	onclick="return confirm(\'Stop following '.$myFriend->getDisplayName().'?\')" title="Remove this person">[x]</a>';
	$myFriendsArray[] = $myFriend->getDisplayName(); // Create an array and fill it with the names of the current user's friends whitch will user later
	echo ' | ';
} 
if (!isset($myFriend)) {
	echo "<div style='font-size: 18px; color:#ccc;'>You don't follow nobody yet. Click the above link to find people.</div>";
}
$myFriendsArray[] = $this->identity()->getDisplayName(); // Add to array current user DisplayName for displayng his articles
?>
<hr />
<h4>They follow you: (they can see only your public events unless you add and categorize them)</h4>
<?php 
foreach ($this->friendsWithMe as $friendWithMe) {
	echo '<span class="zf-green">'.$friendWithMe->getDisplayName(). '</span>';
	if(!in_array($friendWithMe->getDisplayName(), $myFriendsArray)) {
?>
		<a href="<?php echo $this->url('add-person/default', array('controller' => 'index', 'action'=>'add-person', 'id' => $friendWithMe->getId()));?>" onclick="return confirm('Follow <?php echo $friendWithMe->getDisplayName(); ?> ?')" title="Add this person">(+)</a>
<?php
	}
	echo ' | ';
} 
if (!isset($friendWithMe)) {
	echo "<div style='font-size: 18px; color:#ccc;'>Nobody follow you yet.</div>";
}
// END showing friends and following
?>
<hr />
<div class="jumbotron">
<?php
// BEGIN showing the form
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div style="position: relative;">';
echo '<div style="position: relative; float: left; ">';
echo $this->formRow($form->get('title'));
echo '<br/>';
echo $this->formRow($form->get('event'));
echo '</div>';
echo '<div style="position: relative; float: left; margin-left: 20px;">';
echo 'Choose who can see it:<br />';
echo $this->formRow($form->get('followers'));
echo '</div>';
echo '<div style="clear: both"></div>';
echo $this->formSubmit($form->get('submit'));
echo '</div>';
echo $this->form()->closeTag();
// END showing the form
?>
</div>
<hr />
<h4 style="text-align:center">Events: <span><a href="#" class="btn btn-success">All</a> <a href="#" class="btn btn-success">My</a> <a href="#" class="btn btn-success">Group1</a> <a href="#" class="btn btn-success">Group2</a> <a href="#" class="btn btn-success">Group3</a></span></h4>
<div class="jumbotron">

<?php 
// BEGIN showing the articles
foreach ($this->articles as $article) : ?>
<?php if(is_object($article->getAuthor()) && in_array($article->getAuthor()->getDisplayName(), $myFriendsArray)){ //checking the display name in every iteration whether current article display name exist in the array with friends. If not exist current article isn't showing

/**
*
* NOTE: Here you can use jQuery Masonry plugin to arrange the boxes
* http://masonry.desandro.com/
*
*/
?>

<div style="border: solid 0px #ADFF2F; box-shadow: 0px 0px 5px rgba(125, 213, 66, 1); border-radius: 0px;padding: 10px; width: 485px; height: auto; background: #fff; float: left; margin-left: 15px; margin-top: 15px; " onMouseOver="this.style.boxShadow='0px 0px 5px rgba(0, 80, 133, 1)'" onMouseOut="this.style.boxShadow='0px 0px 5px rgba(125, 213, 66, 1)'">
	<div style="font-weight: bold; font-size: 16px; float: left; margin-right: 10px;">
		<?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getDisplayName());?> - 
	</div>
	<div class="zf-green" style=" font-size: 16px;">
		<div style="float: left;">
    	<?php echo $this->escapeHtml($article->getCreated()->format('Y-m-d H:i:s'));?>
    	</div>
    	<?php 
    		if($article->getAuthor()->getUsername() === $this->identity()->getUsername()) { // only show next lines if this is the owner of the article
    	?>
    	<div style="float: right;">
    	<a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'article', 'action'=>'edit', 'id' => $article->getId()));?>">Edit</a> | 
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment>
            array('controller' => 'article', 'action'=>'delete', 'id' => $article->getId()));?>" onclick="return confirm('Do you really want to delete this record?')">Delete</a>
        </div>
        <?php } ?>
	</div>
	<div style="clear: both"></div>
    <div style="font-weight: bold; color: #040">
    	<?php echo $this->escapeHtml($article->getTitle());?>
    </div>
	<div style=" font-size: 18px; color: #555">
    	<?php echo $article->getIntrotext();?>
    </div>
	<div class="zf-green" style=" font-size: 16px;">
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'comment', 'action'=>'index', 'id' => $article->getId()));?>">Add comment</a> |
        <a href="<?php echo $this->url('csn-cms/default', // SUPER IMPORTANT use csn-cms/<segment> NOT ONLY csn-cms
            array('controller' => 'article', 'action'=>'view', 'id' => $article->getId()));?>">View whole event</a>
    </div>
</div>


<?php } ?>
<?php endforeach; 
// END showing the articles
?>
<div style="clear: both"></div>
</div>
