<hr />
<div class="jumbotron">

<?php
if($message = $this->message){
	echo $message;
}else {
$article = $this->article;
$comments = $this->comments;
?>

<div style="border: solid 0px #ADFF2F; box-shadow: 0px 0px 5px rgba(125, 213, 66, 1); border-radius: 0px;padding: 10px; width: 100%; height: auto; background: #fff; " onMouseOver="this.style.boxShadow='0px 0px 5px rgba(0, 80, 133, 1)'" onMouseOut="this.style.boxShadow='0px 0px 5px rgba(125, 213, 66, 1)'">
	<div style="font-weight: bold; font-size: 16px; float: left; margin-right: 10px;">
		<?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getFirstName().' '.$article->getAuthor()->getLastName()); ?> - 
	</div>
	<div class="zf-green" style=" font-size: 16px;">
		<div style="float: left;">
    		<?php echo $this->escapeHtml($article->getCreated()->format('Y-m-d H:i'));?>
    	</div>
    		<?php 
    			// only show next lines if this is the owner of the article
    			if($article->getAuthor()->getUsername() === $this->identity()->getUsername()) {
    		?>
    	<div style="float: right;">
			<a href="<?php echo $this->url('edit-article/default', array('controller' => 'index', 'action'=>'edit-article', 'id' => $article->getId()));?>">
				<?php echo $this->translate('Edit'); ?>
			</a> | 
		    <a href="<?php echo $this->url('delete-article/default', array('controller' => 'index', 'action'=>'delete-article', 'id' => $article->getId()));?>" onclick="return confirm('<?php echo $this->translate('Do you really want to delete this event?'); ?>')">
		    	<?php echo $this->translate('Delete'); ?>
		    </a>
        </div>
        <?php } ?>
	</div>
	<div style="clear: both"></div>
    <div style="font-weight: bold; color: #040">
    	<?php echo $this->escapeHtml($article->getTitle());?>
    </div>
	<div style=" font-size: 18px; color: #555; word-wrap:break-word;">
    	<?php echo $article->getFulltext();?>
    </div>
</div>
</div>
<div class="jumbotron">
<!-- Note that id="comments" is for anchoring -->
<div id="comments"><?php echo $this->translate('Comments'); ?></div>

<?php

// BEGIN showing the form
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo '<div style="position: relative;">';
echo '<div style="position: relative; float: left; ">';
echo $this->formRow($form->get('title'));
echo '<br/>';
echo $this->formRow($form->get('text'));
echo '</div>';

echo '<div style="clear: both"></div>';
echo $this->formSubmit($form->get('submit'));
echo '</div>';
echo $this->form()->closeTag();
// END showing the form
echo '<br />';
foreach($comments as $comment){
?>
<div style="border: solid 0px #ADFF2F; box-shadow: 0px 0px 5px rgba(125, 213, 66, 1); border-radius: 0px;padding: 10px; margin-bottom: 10px; width: 100%; height: auto; background: #fff; " onMouseOver="this.style.boxShadow='0px 0px 5px rgba(0, 80, 133, 1)'" onMouseOut="this.style.boxShadow='0px 0px 5px rgba(125, 213, 66, 1)'">

	<div style="font-weight: bold; font-size: 16px; float: left; margin-right: 10px;">
		<?php if (is_object($comment->getAuthor())) echo $this->escapeHtml($comment->getAuthor()->getFirstName().' '.$comment->getAuthor()->getLastName()); ?>
	</div>
	<div class="zf-green" style=" font-size: 16px;">
		<div style="float: left;">
		<?php if (is_object($comment->getCreated())) echo $this->escapeHtml($comment->getCreated()->format('Y-m-d H:i')); ?>
		</div>
	
	
<?php
	// only show next lines if this is the owner of the article
	if($comment->getAuthor()->getUsername() === $this->identity()->getUsername()) { 
    	?>
    	<div style="float: right;">
			<a href="<?php echo $this->url('edit-comment/default', array('controller' => 'index', 'action'=>'edit-comment', 'article' => $comment->getArticle()->getId(),'id' => $comment->getId()));?>">
				<?php echo $this->translate('Edit'); ?>
			</a> | 
        	<a href="<?php echo $this->url('delete-comment/default', array('controller' => 'index', 'action'=>'delete-comment', 'id' => $comment->getId()));?>" onclick="return confirm('<?php echo $this->translate('Do you really want to delete this comment?'); ?>')">
        		<?php echo $this->translate('Delete'); ?>
        	</a>
        </div>
        <?php } ?>
    </div>
    <div style="clear: both"></div>
    <div style="font-weight: bold; color: #040">
		<?php echo $this->escapeHtml($comment->getTitle()); ?>
	</div>
	<div style=" font-size: 18px; color: #555; word-wrap:break-word;">
		<?php echo $this->escapeHtml($comment->getText()); ?>
	</div>
</div>

<?
}

}
?>
</div>
<a href="<?php echo $this->url('social'); ?>" class="btn btn-success"><?php echo $this->translate('Back to my wall'); ?></a>
